In [50]:
import import_ipynb
from helper import *
import tensorflow as tf

In [51]:
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from keras.models import Sequential
from keras.optimizers import Adam
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from keras.layers import Lambda, Conv2D, MaxPooling2D, Dropout, Dense, Flatten, Activation
matplotlib.style.use('ggplot')

In [52]:
class_names = get_class_names()
print(class_names)

Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/batches.meta
['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


In [53]:
IMAGE_SIZE = 32
CHANNELS = 32

In [54]:
images_train, labels_train, class_train = get_train_data()

Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/data_batch_1
Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/data_batch_2
Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/data_batch_3
Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/data_batch_4
Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/data_batch_5


In [55]:
images_train[1]

array([[[0.60392157, 0.69411765, 0.73333333],
        [0.49411765, 0.5372549 , 0.53333333],
        [0.41176471, 0.40784314, 0.37254902],
        ...,
        [0.35686275, 0.37254902, 0.27843137],
        [0.34117647, 0.35294118, 0.27843137],
        [0.30980392, 0.31764706, 0.2745098 ]],

       [[0.54901961, 0.62745098, 0.6627451 ],
        [0.56862745, 0.6       , 0.60392157],
        [0.49019608, 0.49019608, 0.4627451 ],
        ...,
        [0.37647059, 0.38823529, 0.30588235],
        [0.30196078, 0.31372549, 0.24313725],
        [0.27843137, 0.28627451, 0.23921569]],

       [[0.54901961, 0.60784314, 0.64313725],
        [0.54509804, 0.57254902, 0.58431373],
        [0.45098039, 0.45098039, 0.43921569],
        ...,
        [0.30980392, 0.32156863, 0.25098039],
        [0.26666667, 0.2745098 , 0.21568627],
        [0.2627451 , 0.27058824, 0.21568627]],

       ...,

       [[0.68627451, 0.65490196, 0.65098039],
        [0.61176471, 0.60392157, 0.62745098],
        [0.60392157, 0

In [56]:
class_names = get_class_names()
class_names

Decoding file: C:\Users\jagadesh\Jupyter Projects\CIFAR-10/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [57]:
print(labels_train)

[6 9 9 ... 9 1 1]


In [58]:
print(class_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [60]:
print(len(images_train))
print(len(images_test))

50000
10000
